### ISSUE TITLE
Migrating from bower to webpack

### ISSUE THREAD

**Issue by lukecurtis93** [html5blank/html5blank#169]
Is anyone working on this now that bower is deprecated?

https://github.com/bower/bower/issues/2298

Or are we happy to continue using Bower? :)

**Comment by oriSomething** [comment]
Story long short. I have no time, and barely touch WP nowadays.
Yes, Bower is deprecated but since it's built upon Github it's going to be useful for long time.
Yes, We better moving to `webpack` or `rollup` (rollup might be better since the way WP sites are mostly constructed).
You are more than welcome to open a PR. Good PRs are always welcome

**Comment by pgerochi** [comment]
Hey @oriSomething - I recently did a PR but need some help on it as it's bare bones and basic. I went to webpack because there's more support, over 350 contributors vs 97 for rollup, more stars and the release of webpack 3. Always looking for suggestions and open to whatever though.

**Comment by oriSomething** [comment]
@pgerochi I don't think I'll be active in the future for this project. I don't developing for WP for a long time, and also lack of time to maintain this project.
Anyway, Since projects like `React`, `Ember` (libs of Ember) and `Angular` uses `Rollup` I think Rollup is safe enough. The reason I suggested it, it's because usually Wordpress sites don't need dynamic imports, and the result of Rollup is smaller and faster bundle file. Add to that much easier to config.
I don't say Rollup is better choice than Webpack. I just wanted to tell you how I thought about it.
